name = "PProf"
uuid = "e4faabce-9ead-11e9-39d9-4379958e3056"
authors = ["Valentin Churavy <v.churavy@gmail.com>", "Nathan Daly <nhdaly@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"
